[tool.poetry]
name = "runner"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = "^1.2"
motor = "^2.1"
dnspython = "^1.16"
Jinja2 = "^2.10"
jellyfish = "^0.7.2"
timeago = "^1.0"
bs4 = "^0.0.1"
flask = "^1.1"
aiohttp = "^3.6"
async-lru = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
